### PR TITLE
fix failed to resolve import "@unhead/vue"

### PR DESCRIPTION
**Pull request by hedongshu**
fix failed to resolve import "@unhead/vue"

### CODE REVIEW

**Comment by nurRiyad** [comment]
Hi, can you please share where and when you get this issue?  I don't find this issue in master branch @hedongshu

**Comment by hedongshu** [comment]
When I use pnpm instead of yarn for installation, I encounter this issue

**Comment by nurRiyad** [comment]
I have used yarn and npm both have no issue so it must be something with pnpm. So I think this fix dont actually needed

**Comment by hedongshu** [comment]
Yes, you are right

**Pull request closed without merging**
